# Generated by Django 6.0.4 on 2026-04-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='principal/')),
                ('title', models.CharField(default='Principal', max_length=100)),
            ],
        ),
    ]
