# Generated by Django 6.0.4 on 2026-04-09 03:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_principalmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='about/'),
            preserve_default=False,
        ),
    ]
