# Generated by Django 6.0.4 on 2026-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_muralactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('position', models.IntegerField(help_text='Position in top 10, e.g., 1 for top student')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['grade', 'position'],
                'unique_together': {('grade', 'position')},
            },
        ),
    ]
