# Generated by Django 6.0.4 on 2026-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sgbmember_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Code of Conduct',
            },
        ),
    ]
