# Generated by Django 6.0.4 on 2026-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_codeofconduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeofconduct',
            name='content',
        ),
        migrations.AddField(
            model_name='codeofconduct',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF document', null=True, upload_to='documents/code_of_conduct/'),
        ),
    ]
