# Generated by Django 6.0.4 on 2026-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_codeofconduct_content_codeofconduct_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='newsletters/')),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.RemoveField(
            model_name='muralactivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='muralactivity',
            name='description',
        ),
    ]
