# Generated by Django 6.0.4 on 2026-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_head_of_rcl_rcl'),
    ]

    operations = [
        migrations.CreateModel(
            name='rcl_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rcl/')),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
